### ISSUE TITLE
London 2015 is missing from the list of previous events

### ISSUE THREAD

**Issue by pacharanero** [newNHSHackdaySite/newNHSHackdaySite.github.io#74]
http://newnhshackdaysite.github.io/events/

should be another London between Cardiff 2015 and Manchester 2015, pushing Manchester up to number 11, etc

Let's make this list be autogenerated in jekyll?

**Comment by DeckOfPandas** [comment]
Oooh good volunteering

**Comment by pacharanero** [comment]
Actually this was being caused by a random page build failure - in turn caused by malformed YAML in the event page markdown

**Comment by pacharanero** [comment]
(and it already autogenerates from the markdown)
